# Generated by Django 5.1.1 on 2024-10-16 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConSens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registros',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='valorcriticohumedad',
            options={'verbose_name': 'Valor critico de humedad', 'verbose_name_plural': 'Valores criticos de humedad'},
        ),
        migrations.AlterModelOptions(
            name='valorcriticopresion',
            options={'verbose_name': 'Valor critico de presion', 'verbose_name_plural': 'Valores criticos de presion'},
        ),
        migrations.AlterModelOptions(
            name='valorcriticotemperatura',
            options={'verbose_name': 'Valor critico de temperatura', 'verbose_name_plural': 'Valores criticos de temperatura'},
        ),
        migrations.AlterField(
            model_name='valorcriticohumedad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valorcriticopresion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valorcriticotemperatura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
