# Generated by Django 5.1.1 on 2024-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConSens', '0002_alter_registros_options_alter_usuarios_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='humedad',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humedad registrada'),
        ),
    ]
