# Generated by Django 5.1.1 on 2024-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConSens', '0003_alter_registros_humedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='modulo',
            field=models.CharField(max_length=64, verbose_name='Nombre del modulo'),
        ),
        migrations.AlterField(
            model_name='valorcriticohumedad',
            name='humedad_maxima',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='valorcriticohumedad',
            name='humedad_minima',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
